"""entities and alerts tables for NLP

Revision ID: 1cbf7c536f4d
Revises: e4d6274bba98
Create Date: 2025-09-11 23:46:02.243732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cbf7c536f4d'
down_revision: Union[str, Sequence[str], None] = 'e4d6274bba98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('matched_phrase', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_category_created', 'alerts', ['category', 'created_at'], unique=False)
    op.create_index('idx_alerts_channel_created', 'alerts', ['channel_id', 'created_at'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('text_norm', sa.Text(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entities_channel_started', 'entities', ['channel_id', 'started_at'], unique=False)
    op.create_index('idx_entities_label_started', 'entities', ['label', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_entities_label_started', table_name='entities')
    op.drop_index('idx_entities_channel_started', table_name='entities')
    op.drop_table('entities')
    op.drop_index('idx_alerts_channel_created', table_name='alerts')
    op.drop_index('idx_alerts_category_created', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
