"""visual_events: add video/screenshot metadata

Revision ID: 2fa34c4c12ce
Revises: 1c481be7436d
Create Date: 2025-09-06 14:59:02.278948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa34c4c12ce'
down_revision: Union[str, Sequence[str], None] = '1c481be7436d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visual_events', sa.Column('video_path', sa.String(), nullable=True))
    op.add_column('visual_events', sa.Column('video_filename', sa.String(), nullable=True))
    op.add_column('visual_events', sa.Column('screenshot_path', sa.String(), nullable=True))
    op.add_column('visual_events', sa.Column('frame_timestamp_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visual_events', 'frame_timestamp_ms')
    op.drop_column('visual_events', 'screenshot_path')
    op.drop_column('visual_events', 'video_filename')
    op.drop_column('visual_events', 'video_path')
    # ### end Alembic commands ###
