"""add text_norm and engine_time_ms to transcripts

Revision ID: 3ef1d1fd267d
Revises: 2fa34c4c12ce
Create Date: 2025-09-07 11:27:08.143933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef1d1fd267d'
down_revision: Union[str, Sequence[str], None] = '2fa34c4c12ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('text_norm', sa.Text(), nullable=True))
    op.add_column('transcripts', sa.Column('engine_time_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'engine_time_ms')
    op.drop_column('transcripts', 'text_norm')
    # ### end Alembic commands ###
