"""segments: audio/video paths nullable + has_media check

Revision ID: b6aa81e4e7b3
Revises: 769f3fadf22a
Create Date: 2025-09-05 19:42:24.981292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6aa81e4e7b3'
down_revision: Union[str, Sequence[str], None] = '769f3fadf22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('segments', 'audio_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('segments', 'audio_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
