"""screenshots table for segment images

Revision ID: e4d6274bba98
Revises: 3ef1d1fd267d
Create Date: 2025-09-11 23:20:32.238654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4d6274bba98'
down_revision: Union[str, Sequence[str], None] = '3ef1d1fd267d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('segment_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frame_timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('screenshot_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_screenshots_channel_created', 'screenshots', ['channel_id', 'created_at'], unique=False)
    op.create_index('idx_screenshots_created', 'screenshots', ['created_at'], unique=False)
    op.create_index('idx_screenshots_segment', 'screenshots', ['segment_id', 'segment_started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_screenshots_segment', table_name='screenshots')
    op.drop_index('idx_screenshots_created', table_name='screenshots')
    op.drop_index('idx_screenshots_channel_created', table_name='screenshots')
    op.drop_table('screenshots')
    # ### end Alembic commands ###
